var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
var city = 'karachi';
console.log("Is city == 'lahore'? I predict False.");
console.log(city == 'lohore');
var country = 'Pakistan';
console.log("Is country == 'Pakistan'? I predict True.");
console.log(country == 'Pakistan');
var district = 'Rawalpindi';
console.log("Is district == 'Rawalpindi'? I predict True.");
console.log(district == 'Rawalpindi');
var province = 'punjab';
console.log("Is province == 'sindh'? I predict False.");
console.log(province == 'sindh');
var language = 'urdu';
console.log("Is language == 'eng'? I predict False.");
console.log(language == 'eng');
var person = 'male';
console.log("Is person == 'Male'? I predict  False.");
console.log(person == 'Male');
var university = 'piaes';
console.log("Is university == 'pieas'? I predict True.");
console.log(university == 'pieas');
var w = 20;
console.log("Is w == '20'? I predict True.");
console.log(w == 20);
var p = 130;
console.log("Is p== 'false'? I predict False.");
console.log(p = 140);
